
export const MyOderImage = {
    basket: 'basket1.png',
    cook: 'MyOrder/008.jpg',
    cook2: 'MyOrder/007.jpg',
    basket2: '/MyOrder/te.png',
    close: '/MyOrder/cancel.png',
    credit: '/MyOrder/credit-card.png',
    paypal: '/MyOrder/paypal.png',
    bank: '/MyOrder/bank.png',
    time: '/MyOrder/time.png',
    delivery: '/MyOrder/food.png',
    myHome: '/MyOrder/HomeAddress.png',
    user: '/MyOrder/user.png',
    email: '/MyOrder/email.png',
    smartphone: '/MyOrder/smartphone.png',
    add: '/MyOrder/add.png',
    building: '/MyOrder/building.png',
    zip: '/MyOrder/zip-code.png',
    processing: '/MyOrder/processing.png',
    remove: '/MyOrder/trash.png',
    trash: '/MyOrder/trash-bin.png',
    mat: '/MyOrder/salad.png',
    password: '/MyOrder/password.png',
    face: '/MyOrder/face.png ',
    android: '/MyOrder/play.png ',
    instagram: '/MyOrder/instagram.png',
    twitter: '/MyOrder/twitter.png',
    city: '/MyOrder/city.png',
    restaurant: '/MyOrder/restaurant.png',
    food: '/MyOrder/dish.png',
    time2: '/MyOrder/delivery.png',
    map: '/MyOrder/map.png',
    image: '/MyOrder/image.png',
    live: '/MyOrder/live.png',
    edit: '/MyOrder/edit.png',
    profile: '/MyOrder/man.png',
    chat: '/MyOrder/chat.png',
    change: '/MyOrder/change.png',
    view: '/MyOrder/view.png',
    totla: '/MyOrder/totla.png',
    cancel: '/MyOrder/cancel2.png',
    number: '/MyOrder/number.png',
    out: '/MyOrder/check-out.png',
    search: '/MyOrder/search.png',
    create: '/MyOrder/create.png',
    sales: '/MyOrder/sales.png',
    uploading: '/MyOrder/uploading.png',
    name: '/MyOrder/name.png',
    notification: '/MyOrder/notification.png',
    left: '/MyOrder/left.png',
    rigth: '/MyOrder/rigth.png',
    heart: '/MyOrder/heart.png',
    heartFull: '/MyOrder/heart-full.png',
    safety: '/MyOrder/safety.png',
    work: '/MyOrder/work.png',
    foodname: '/MyOrder/foodname.png',
    maps: '/MyOrder/maps.jpeg',
    bike: '/MyOrder/bike.png',
    right: '/MyOrder/right-arrow.png',
    card2: '/MyOrder/card-notcolor.png',
    bike2: '/MyOrder/bike-driver.png',
    top: '/MyOrder/top.png',
    courier: '/MyOrder/courier.png',
    takeaway: '/MyOrder/takeaway.png',
    home: '/MyOrder/home.png',
    mpablack: '/MyOrder/mpablack.png',
    timeblack: '/MyOrder/timeblack.png',
    checkedblack: '/MyOrder/checked-black.png',
    checked: '/MyOrder/checked.png',
    clock: '/MyOrder/clock.png',
    comment: '/MyOrder/comment.png',
    minus: '/MyOrder/minus.png',
    plus: '/MyOrder/plus.png',
    down: '/MyOrder/down-arrow.png',
    rest: '/MyOrder/rest.png',
    cityB: '/MyOrder/city-black.png',
    logindriver: '/MyOrder/login-driver.jpg',
    facebookicons: '/MyOrder/facebook.png',
    googleiconss: '/MyOrder/goo.png',
    forget: '/MyOrder/forget.jpg',
    other: '/MyOrder/other.png',
    address: '/MyOrder/address.png',
    cooking: '/MyOrder/cooking.png',
    pin: '/MyOrder/pin.png',
    loaction: '/MyOrder/loaction.jpg',
    loaction2: '/MyOrder/loaction2.jpg',
    loaction3: '/MyOrder/loaction3.jpg',
    loaction4: '/MyOrder/loaction4.jpg',
    loaction5: '/MyOrder/loaction5.jpg',
    loaction6: '/MyOrder/loaction6.jpg',
    loaction7: '/MyOrder/loaction7.jpg',
    sweden: '/MyOrder/sweden.png',
    placeholder: '/MyOrder/placeholder.png',

    
    visa: '/MyOrder/visa.png',
    maestro: '/MyOrder/maestro.png',

    testloction: '/MyOrder/send-location.png',
    filter: '/MyOrder/filter.png',
    product: '/MyOrder/product.png',
    category: '/MyOrder/category.png',

    





}


