export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER = 'SET_USER'
export const KEY_USER = 'KEY_USER'
export const KEY_TOKEN = 'KEY_TOKEN'


// Updated product
export const ADD_PRODUCT_UPDATED_SUCCESS = 'ADD_PRODUCT_UPDATED_SUCCESS'
export const ADD_PRODUCT_UPDATED_LOADING = 'ADD_PRODUCT_UPDATED_LOADING'
export const ADD_PRODUCT_UPDATED_FAIL = 'ADD_PRODUCT_UPDATED_FAIL'
export const ADD_PRODUCT_CREATE_SUCCESS = 'ADD_PRODUCT_CREATE_SUCCESS'
export const ADD_PRODUCT_CREATE_IMAGE_SUCCESS = 'ADD_PRODUCT_CREATE_IMAGE_SUCCESS'






// updated cart info
export const ADD_UPDATED_CARTINFO_LOADING = 'ADD_UPDATED_CARTINFO_LOADING'
export const ADD_UPDATED_CARTINFO_SUCCESS = 'ADD_UPDATED_CARTINFO_SUCCESS'
export const ADD_UPDATED_CARTINFO_FAIL = 'ADD_UPDATED_CARTINFO_FAIL'

// CART INFO 
export const ADD_CARTINFO_RESTURANG_LOADING = 'ADD_CARTINFO_RESTURANG_LOADING'
export const ADD_CARTINFO_RESTURANG_SUCCESS = 'ADD_CARTINFO_RESTURANG_SUCCESS'
export const ADD_CARTINFO_RESTURANG_FAIL = 'ADD_CARTINFO_RESTURANG_FAIL'



// show all orders 
export const ADD_SHOWS_ORDERS_RESTURANS_NUMBER = 'ADD_SHOWS_ORDERS_RESTURANS_NUMBER'
export const ADD_SHOWS_ORDERS_RESTURANS_SUCCESS = 'ADD_SHOWS_ORDERS_RESTURANS_SUCCESS'
export const ADD_SHOWS_ORDERS_RESTURANS_FAIL = 'ADD_SHOWS_ORDERS_RESTURANS_FAIL'

// order restrange notfications
export const ADD_ORDER_NOTIFICATIONS_LOADING = 'ADD_ORDER_NOTIFICATIONS_LOADING'
export const ADD_ORDER_NOTIFICATIONS_SUCCESS = 'ADD_ORDER_NOTIFICATIONS_SUCCESS'
export const ADD_ORDER_NOTIFICATIONS_FAIL = 'ADD_ORDER_NOTIFICATIONS_FAIL'

// local cart
export const ADD_CARDNUMBER_SAVE = 'ADD_CARDNUMBER_SAVE'
export const ADD_LOCAT_CARTNUMBER = 'ADD_LOCAT_CARTNUMBER'
export const ADD_CARDNUMBER_REMOVE = 'ADD_CARDNUMBER_REMOVE'



// new restrange max 8 items
export const ADD_NEW_RESTRANGE_LOADING = 'ADD_NEW_RESTRANGE_LOADING'
export const ADD_NEW_RESTRANGE_SUCCESS = 'ADD_NEW_RESTRANGE_SUCCESS'
export const ADD_NEW_RESTRANGE_FAIL = 'ADD_NEW_RESTRANGE_FAIL'



export const ADD_NEW_FIRDELIVERY_LOADING = 'ADD_NEW_FIRDELIVERY_LOADING'
export const ADD_NEW_FIRDELIVERY_SUCCESS = 'ADD_NEW_FIRDELIVERY_SUCCESS'
export const ADD_NEW_FIRDELIVERY_FAIL = 'ADD_NEW_FIRDELIVERY_FAIL'



// catgory all 
export const ADD_CATAGORY_ALL_LOADING = 'ADD_CATAGORY_ALL_LOADING'
export const ADD_CATAGORY_ALL_SUCCESS = 'ADD_CATAGORY_ALL_SUCCESS'
export const ADD_CATAGORY_ALL_FAIL = 'ADD_CATAGORY_ALL_FAIL'





// save data checkout
export const SAVE_CHECKOUT = 'SAVE_CHECKOUT'
export const SAVE_LOCAL_CH = 'SAVE_LOCAL_CH'

// searching products.
export const ADD_SEARCHING_PRODUCT_DETAILS_NUMBER = 'ADD_SEARCHING_PRODUCT_DETAILS_NUMBER'
export const ADD_SEARCHING_PRODUCT_DETAILS_SUCCESS = 'ADD_SEARCHING_PRODUCT_DETAILS_SUCCESS'
export const ADD_SEARCHING_PRODUCT_DETAILS_FAIL = 'ADD_SEARCHING_PRODUCT_DETAILS_FAIL'



// CART INFO 
export const ADD_CARTINFO_ID_LOADIN = 'ADD_CARTINFO_ID_LOADIN'
export const ADD_CARTINFO_ID_SUCCESS = 'ADD_CARTINFO_ID_SUCCESS'
export const ADD_CARTINFO_ID_FAIL = 'ADD_CARTINFO_ID_FAIL'
export const ADD_CARTINFO_ID_SAVE = 'ADD_CARTINFO_ID_SAVE'


// LOACTION 
export const ADD_LOACTION = 'ADD_LOACTION'





// cart info...


export const ADD_CART_INFO_LOADING_RESTAURANT = 'ADD_CART_INFO_LOADING_RESTAURANT'
export const ADD_CART_INFO_SUCCESS_RESTAURANT = 'ADD_CART_INFO_SUCCESS_RESTAURANT'
export const ADD_CART_INFO_FAIL_RESTAURANT = 'ADD_CART_INFO_FAIL_RESTAURANT'


export const ADD_CART_INFO_LOADING_BUTIK = 'ADD_CART_INFO_LOADING_BUTIK'
export const ADD_CART_INFO_SUCCESS_BUTIK = 'ADD_CART_INFO_SUCCESS_BUTIK'
export const ADD_CART_INFO_FAIL_BUTIK = 'ADD_CART_INFO_FAIL_BUTIK'

// add telefonumber =
export const ADDTELEFONUMBER = 'ADDTELEFONUMBER'
// USER CHECKEN 
export const ADD_USER_CHECKIN = 'ADD_USER_CHECKIN'

// save delivery
export const DELIVER_SAVE = 'DELIVER_SAVE'
export const DELIVER_SAVE_LOACAL = 'DELIVER_SAVE_LOACAL'
export const DD_CC = 'DD_CC'

// discount check in
export const ADD_DISCOUNTCOD_LOADING = 'ADD_DISCOUNTCOD_LOADING'
export const ADD_DISCOUNTCOD_SUCCESS = 'ADD_DISCOUNTCOD_SUCCESS'
export const ADD_DISCOUNTCOD_FAIL = 'ADD_DISCOUNTCOD_FAIL'

// start WORK
export const ADD_VIEWS_WORK_LOADING = 'ADD_VIEWS_WORK_LOADING'
export const ADD_VIEWS_WORK_SUCCESS = 'ADD_VIEWS_WORK_SUCCESS'
export const ADD_VIEWS_WORK_FAIL = 'ADD_VIEWS_WORK_FAIL'


export const ADD_VIEWS_WORK_REMOVE_SUCCESS = 'ADD_VIEWS_WORK_REMOVE_SUCCESS'
export const ADD_VIEWS_WORK_CREATE_SUCCESS = 'ADD_VIEWS_WORK_CREATE_SUCCESS'
export const ADD_VIEWS_WORK_UPDATE_SUCCESS = 'ADD_VIEWS_WORK_UPDATE_SUCCESS'

// end work



// contact
export const ADD_VIEWS_CONTACT_LOADING = 'ADD_VIEWS_CONTACT_LOADING'
export const ADD_VIEWS_CONTACT_SUCCESS = 'ADD_VIEWS_CONTACT_SUCCESS'
export const ADD_VIEWS_CONTACT_FAIL = 'ADD_VIEWS_CONTACT_FAIL'


export const ADD_VIEWS_CONTACT_REMOVE_SUCCESS = 'ADD_VIEWS_CONTACT_REMOVE_SUCCESS'
export const ADD_VIEWS_CREATE_CONTACT_SUCCESS = 'ADD_VIEWS_CREATE_CONTACT_SUCCESS'
export const ADD_VIEWS_CONTACT__UPDATE_SUCCESS = 'ADD_VIEWS_CONTACT__UPDATE_SUCCESS'
// END contact

// Start about ..............> 
export const ADD_VIEWS_ABOUT_LOADING = 'ADD_VIEWS_ABOUT_LOADING'
export const ADD_VIEWS_ABOUT_SUCCESS = 'ADD_VIEWS_ABOUT_SUCCESS'
export const ADD_VIEWS_ABOUT_FAIL = 'ADD_VIEWS_ABOUT_FAIL'


export const ADD_VIEWS_ABOUT_UPDATE_SUCCESS = 'ADD_VIEWS_ABOUT_UPDATE_SUCCESS'
export const ADD_VIEWS_ABOUT_REMOVE_SUCCESS = 'ADD_VIEWS_ABOUT_REMOVE_SUCCESS'
export const ADD_VIEWS_ABOUT_CREATE__SUCCESS = 'ADD_VIEWS_ABOUT_CREATE__SUCCESS'

// END about...................>

// Start Cook ........................>

export const ADD_VIEWS_COOK_LOADING = 'ADD_VIEWS_COOK_LOADING'
export const ADD_VIEWS_COOK_SUCCESS = 'ADD_VIEWS_COOK_SUCCESS'
export const ADD_VIEWS_COOK_FAIL = 'ADD_VIEWS_COOK_FAIL'

export const ADD_VIEWS_COOK_REMOVE_SUCCESS = 'ADD_VIEWS_COOK_REMOVE_SUCCESS'
export const ADD_VIEWS_COOK_CREATE__SUCCESS = 'ADD_VIEWS_COOK_CREATE__SUCCESS'
export const ADD_VIEWS_COOK_UPDATE_SUCCESS = 'ADD_VIEWS_COOK_UPDATE_SUCCESS'

// end Cook ...............................>


// forget password 
export const ADD_FORGET_PASSWORD_SUCCESS = 'ADD_FORGET_PASSWORD_SUCCESS'
export const ADD_CHANGEPASSWORD_FORGET_SUCCESS = 'ADD_CHANGEPASSWORD_FORGET_SUCCESS'
// SEARCHING products...
export const ADD_PRODUCT_SEARCHING = 'ADD_PRODUCT_SEARCHING'
export const ADD_PRODUCT_SEARCHING_FAIL = 'ADD_PRODUCT_SEARCHING_FAIL'
export const ADD_PRODUCT_SEARCHING_NUMBER = 'ADD_PRODUCT_SEARCHING_NUMBER'

// list pagaination List User...
export const ADD_ADMIN_LIST_APPEND = 'ADD_ADMIN_LIST_APPEND'
export const ADD_ADMIN_LIST_NUMBER = 'ADD_ADMIN_LIST_NUMBER'





// list orders 
export const ADD_ADMIN_ORDER_SUCCESS = 'ADD_ADMIN_ORDER_SUCCESS'
export const ADD_ADMIN_ORDER_NUMBER = 'ADD_ADMIN_ORDER_NUMBER'



// LOGIN....
export const ADD_USER_LOADING = 'ADD_USER_LOADING'
export const ADD_USER_SUCESS = 'ADD_USER_SUCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const ADD_USER_RESET = 'ADD_USER_RESET'


// LOGO UT.
export const ADD_USER_LOGOUT = 'ADD_USER_LOGOUT'

// user list. . 
export const ADD_LIST_SUCEESS = 'ADD_LIST_SUCEESS'
export const ADD_LIST_FAIL = 'ADD_LIST_FAIL'

// change user name 
export const ADD_CHANGEUSER_LOADING = 'ADD_CHANGEUSER_LOADING'
export const ADD_CHANGEUSER_SUCEESS = 'ADD_CHANGEUSER_SUCEESS'
export const ADD_CHANGEUSER_FAIL = 'ADD_CHANGEUSER_FAIL'


// add adress....
export const ADD_ADDRES_SUCCESS = 'ADD_ADDRES_SUCCESS'
export const ADD_ADDRES_FAIL = 'ADD_ADDRES_FAIL'

// bli admin 

export const ADD_USER_REMOV_SUCCESS = 'ADD_USER_REMOV_SUCCESS'
export const ADD_USER_REMOV_FAIL = 'ADD_USER_REMOV_FAIL'


// create post ... 
export const ADD_CREATE_POST_LOADING = 'ADD_CREATE_POST_LOADING'
export const ADD_CREATE_POST_SUCEES = 'ADD_CREATE_POST_SUCEES'
export const ADD_CREATE_POST_FAIL = 'ADD_CREATE_POST_FAIL'


// show post.. 
export const ADD_POST_LOADING = 'ADD_POST_LOADING'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'


// Show post id 
export const ADD_POST_ID_LOADING = 'ADD_POST_ID_LOADING'
export const ADD_POST_ID_SUCCESS = 'ADD_POST_ID_SUCCESS'
export const ADD_POST_ID_FAIL = 'ADD_POST_ID_FAIL'



// create commit 
export const ADD_COMMIT_LOADING = 'ADD_COMMIT_LOADING'
export const ADD_COMMIT_SUCCESS = 'ADD_COMMIT_SUCCESS'
export const ADD_COMMIT_FAIL = 'ADD_COMMIT_FAIL'


export const ADD_REMOVE_POST_SUCCESS = 'ADD_REMOVE_POST_SUCCESS'
export const ADD_REMOVE_POST_FAIL = 'ADD_REMOVE_POST_FAIL'



// add cart itrms.
export const CART_ADD_ITEMS = 'CART_ADD_ITEMS'
export const REMOVE_CART_ITEMS = 'REMOVE_CART_ITEMS'



// SAVE TIME ... 
export const ADD_SAVE_TIME = 'ADD_SAVE_TIME'
export const ADD_ADRRESS_SAVE = 'ADD_ADRRESS_SAVE'
















// add order .... 
export const ADD_ORDER_LOADING = 'ADD_ORDER_LOADING'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL'

// order id .. 
export const ADD_ORDERID_SUCCESS = 'ADD_ORDERID_SUCCESS'
export const ADD_ORDERID_FAIL = 'ADD_ORDERID_FAIL'

// order user prevat...
export const ADD_ORDER_ID_SUCCESS = 'ADD_ORDER_ID_SUCCESS'
export const ADD_ORDER_ID_FAIL = 'ADD_ORDER_ID_FAIL'



// remove user id... 
export const ADD_REMOVE_ORDER_SUCCESS = 'ADD_REMOVE_ORDER_SUCCESS'
export const ADD_REMOVE_ORDER_FAIL = 'ADD_REMOVE_ORDER_FAIL'



// add Like cart  and Remove
export const ADD_LIKE_CART = 'ADD_LIKE_CART'
export const ADD_LIKE_REMOVE = 'ADD_LIKE_REMOVE'




// Product top
export const ADD_LATEST_PRODUCTS_LOADING = 'ADD_LATEST_PRODUCTS_LOADING'
export const ADD_LATEST_PRODUCTS_SUCCESS = 'ADD_LATEST_PRODUCTS_SUCCESS'
export const ADD_LATEST_PRODUCTS_FAIL = 'ADD_LATEST_PRODUCTS_FAIL'

// last product 
export const ADD_PRODUCTS_LAST_SUCCESS = 'ADD_PRODUCTS_LAST_SUCCESS'


// All category .... 
export const ADD_CATEGORY_LOADING = 'ADD_CATEGORY_LOADING'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL'
export const ADD_CATEGORY_SAVE_ID = 'ADD_CATEGORY_SAVE_ID'











// product pagation... 
export const ADD_CATEGORYPRODUCT_APPEND = 'ADD_CATEGORYPRODUCT_APPEND'
export const ADD_NUMBERNEXTPAGE_SUCCESS = 'ADD_NUMBERNEXTPAGE_SUCCESS'
export const ADD_PAGINATION_PRODUCT_FAIL = 'ADD_PAGINATION_PRODUCT_FAIL'


// product id
export const ADD_PRODUCT_ID_LOADING = 'ADD_PRODUCT_ID_LOADING'
export const ADD_PRODUCT_ID_SUCCESS = 'ADD_PRODUCT_ID_SUCCESS'
export const ADD_PRODUCT_ID_FAIL = 'ADD_PRODUCT_ID_FAIL'
// review .
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'




// orders user
export const ADD_ORDERS_USER_SUCCESS = 'ADD_ORDERS_USER_SUCCESS'
export const ADD_ORDERS_USER_NUMBER = 'ADD_ORDERS_USER_NUMBER'




// ADMIN lIST

export const ADD_ADMIN_LIST_LOADING = 'ADD_ADMIN_LIST_LOADING'
export const ADD_ADMIN_LIST_SUCCESS = 'ADD_ADMIN_LIST_SUCCESS'
export const ADD_ADMIN_LIST_FAIL = 'ADD_ADMIN_LIST_FAIL'
export const ADD_ADMIN_REMOVE_ISADMIN_SUCCESS = 'ADD_ADMIN_REMOVE_ISADMIN_SUCCESS'













// product searching and list 
export const ADD_SEARCHING_LOADING = 'ADD_SEARCHING_LOADING'
export const ADD_SEARCHING_SUCCESS = 'ADD_SEARCHING_SUCCESS'
export const ADD_SEARCHING_NEXTNUMBER = 'ADD_SEARCHING_NEXTNUMBER'
export const ADD_SEARCHING_FAIL = 'ADD_SEARCHING_FAIL'
export const ADD_ADMIN_PRODUCTS_REMOVE_SUCCESS = 'ADD_ADMIN_PRODUCTS_REMOVE_SUCCESS'
export const ADD_ADMIN_PRODUCTS_UPDATE_SUCCESS = 'ADD_ADMIN_PRODUCTS_UPDATE_SUCCESS'
export const ADD_ADMIN_PRODUCTS_CREATE_SUCCESS = 'ADD_ADMIN_PRODUCTS_CREATE_SUCCESS'







// Admin only order..
export const ADD_ADMIN_ORDER_LIST_LOADING = 'ADD_ADMIN_ORDER_LIST_LOADING'
export const ADD_ADMIN_ORDER_LIST_SUCCESS = 'ADD_ADMIN_ORDER_LIST_SUCCESS'
export const ADD_ADMIN_ORDER_LIST_FAIL = 'ADD_ADMIN_ORDER_LIST_FAIL'
export const ADD_ADMIN_ORDER_DELIVERY_SUCCESS = 'ADD_ADMIN_ORDER_DELIVERY_SUCCESS'